# Generated by Django 5.2.8 on 2026-09-07 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='ICONIC BEAUTY', max_length=255)),
                ('subtitle', models.CharField(default='Welcome to SwissMax Beauty — We curate iconic formulations that deserve attention.', max_length=500)),
                ('button_text', models.CharField(default='DISCOVER', max_length=100)),
                ('left_banner_image', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('left_banner_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('right_banner_image', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('right_banner_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('announcement_text', models.CharField(default='Website Sale Up to 30% off + Free Shipping', max_length=300)),
                ('announcement_link_text', models.CharField(default='shop now', max_length=100)),
                ('countdown_days', models.IntegerField(default=22)),
                ('countdown_hours', models.IntegerField(default=9)),
                ('countdown_minutes', models.IntegerField(default=21)),
                ('countdown_seconds', models.IntegerField(default=37)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
