# Generated by Django 5.2.8 on 2026-09-06 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='Created', max_length=50)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cart.cart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
