# Generated by Django 5.2.8 on 2026-10-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Limited Edition', 'Limited Edition'), ('Sale', 'Sale')], default='', max_length=30),
        ),
    ]
